<a href="https://colab.research.google.com/github/Brundha04/Numpy_Notes/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy basics 03-01-2025**

In [ ]:
#What is Numpy-----> Num +py------>  diff b/w numpy vs pyspark
#core library for scientific computing in python
#the central object in Numpy is "Numpy Arrays"
#What is Numpy Arrays?
'''high performance ,multi-dimensional data
structure object which is designed specifically to perform maths operations'''

In [ ]:
#What is an Array?
"""In Python, they are containers which are able to store more than one item at the same time.
 Specifically, they are an ordered collection of elements
  with every value being of the same data type."""

In [ ]:
#How many types of arrays do we have?
#1D--> 0 colums and presence of rpws (axis=0)
#2D--> Tabular data where it has both rows and columns
#3D--> It is multidimensional data structure where it has axis=0 ,axis=1,and axis=2

In [ ]:
#What are all different use cases of numpy ?
"""1.Dot product/inner product
   2.Matrix multiplication
   3.Element wisematrix product
   4.Solving the linear systems
   5.Inverse
   6.Determinent
   7.Choose the random numbers
   8.statistics

In [ ]:
#installation of numpy
!pip install numpy

In [ ]:
#import numpy
import numpy as np

In [ ]:
#how can we check the version of numpy
np.__version__

'1.26.4'

#central object is array

In [ ]:
l1=[1,2,3,4]
a=np.array(l1)
print(a)
print(l1)
#Difference b/w the list and array?
#list -->[],ordered,muttable,allows duplicates
#Arrays--->[],ordered,immutable,allows duplicates

In [ ]:
a = np.array([1,2,3,4])
print(a)
#i want to know the shape of the array
a.shape #-->(count_rows,count_columns)
#iwant to know element data types in the above array?
a.dtype
#i want to know the dimensionality of the array's?
a.ndim
#i want to know the total no of elements in array
a.size
#i want to know the size in bytes
print(a.itemsize)

**04-01-2025**

**Essential methods in Numpy**

In [ ]:
import numpy as np

In [ ]:
b = np.array([1,2,3])
#acess the elements by using the index position number
print(b[0])
print(b[0:3])
print(b[::-1])
print(b[:])#default indexing position
print(b[::])

1
[1 2 3]
[3 2 1]
[1 2 3]
[1 2 3]


In [ ]:
# i want to know the sums of elements in the array
print(sum(b))

6


In [ ]:
h=np.array([1,2,3,4,5,6,7,8,9])
#print the sum array h
print(sum(h))
print(h.sum())
#find the mean  ofthe array in h
print(h.mean())
#find the min number in array
print(h.min())
#find the max number in array?
print(h.max())
"""a=['cat','dog','cat']
import pandas as pd
df=pd.Dataframe(a)
df.mode()"""

In [ ]:
l=[1,2,3,4,5,6,7,8,9]
print(sum(l))
#print(l.sum())
l.append(10)
l

45


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
a=np.array([1,2,3,4,5,1,3,4,1])
print(dir(a))
#Note:- arrays dont have mode and median

In [ ]:
n=np.append(h,0)
print(n)

[1 2 3 4 5 6 7 8 9 0]


**Arrays vs List**

In [ ]:
#add new item to the list
l=[1,2,3,4,5,6,7,8,9]
l.append(10)
l

In [ ]:
#Add new item to the array
a=np.array([1,2,3])
a.append(4)
a

In [ ]:
#How can we add items in an array?
a=np.array([1,2,3])
b=np.append(a,4)
print(b)

[1 2 3 4]


In [ ]:
c=b + np.array(5)
#single number is adding with each and every element in array is known as "Broad casting" method
print(c)

[6 7 8 9]


In [ ]:
#Vector addition: adding two arrays having equal number of elements and same dimensions is known vector addition
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)

[5 7 9]
[ 4 10 18]


In [ ]:
l=[1,2,3]
#multiple of 2
for i in l:
  print(i*2,end=",")

2,4,6,

In [ ]:
print(a*2)

[2 4 6]


In [ ]:
#find the sqrt for array's
print(a**0.5)

[1.         1.41421356 1.73205081]


In [ ]:
a=['apple',1,5.8,4+6j]
b=np.array(a)
print(b)

['apple' '1' '5.8' '(4+6j)']


In [ ]:
b=[2+4j,5+6j]
c=np.array(b)
d=np.insert(b,2,5+6j)
print(d)
print(dir(d))

**Dot  product **

In [ ]:
a=np.array([1,2])
b=np.array([3,4])
#sum of product of corresponding items
#when apply dot product check the array are same number of elements
dot=0
for i in range(len(a)):
  dot += a[i]*b[i]
  print(dot)

3
11


In [ ]:
#easy methods
dot=np.dot(a,b)
dot

In [ ]:
dot =a.dot(b)
print(dot)


In [ ]:
dot=a@b
print(dot)

11


In [ ]:
#manul
c=a*b
d=np.sum(c)
print(d)

11


**06-01-2025**

In [ ]:
import numpy as ny

In [ ]:
#create a 1d array from list
a = [1,2,3]
b = np.array(a)
print(b.ndim)

**Multidimensional array's**

In [ ]:
#create a 2d array
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(a)

2
[[1 2 3]
 [4 5 6]]


In [ ]:
print(a.itemsize)
print(a.shape)

In [ ]:
#How can i access the elements from array?
#by using the index position number we can acces elemnts in array
#array[row_index value, column index value]
a = np.array([[1,2,3],[4,5,6]])
print(a[0])

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

In [ ]:
#if i want to access the particular value from particular column and row
print(b[1,1])
print(b[1][1])
#print the "9" from above array
print(b[2,2])
print(b[2][2])

In [ ]:
#slicing:- accessing the range of characters
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
#i want to print the values present at 1st column
print(b[:,0])
#print all the column values in row zero
print(b[0])
# 0r the below one bothe are same
print(b[0,:])

**Transpose**--> change rows in to columns and columns in to rows

In [ ]:
h = np.array([[1,2,3],[4,5,6]])
print(h.shape)

In [ ]:
u = h.T
print(u)

**MATRIX MULTIPLICATION**

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])
#Note:- to apply matrix multiplication the arrays has to be in same shape
c = a.dot(b)
print(c)
#print(a*b)   #element wise multiplication

NameError: name 'np' is not defined

In [ ]:
#broadcasting method:-
a = np.array([[1,2],[3,4]])
b = np.array([[2]])
print(a*b)

In [ ]:
d = np.array([[4,5,6],[7,8,9]])
h = d.dot(b)      #inner dimesions has to be matched
print(h)

In [ ]:
A = d.T
A

In [ ]:
H = A.dot(b)
print(H)

In [ ]:
#Note:- when we apply the dot product for 2d array it has to be in same shape

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([1,2])
c = a.dot(b)
print(c)

**determinent**

In [ ]:
a = np.array([[1,2],[3,4]])
#find the det of a
#use   'np.linalg.det'
c = np.linalg.det(a)
print(c)
#determinent  --->  [(1x4)- (2x3)]

**Inverse**

In [ ]:
a = np.array([[1,2],[3,4]])
d = np.linalg.inv(a)
print(d)

**diagonal**

In [ ]:
c = np.diag(a)
print(c)

In [ ]:
#diagonal on a vector returns diagonal matrix
d = np.diag([1,4])
print(d)

**BOoLEAN INDEXING**

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a.ndim)
print(a.shape)
print(a)
print(a[:,1])

In [ ]:
#print the elements greater than 2 from above array
print(a[a>2])

In [ ]:
#HOW WE CAN APPLY CONDITION IN ARRAY?
#np.where(condition, true, false)
b = np.where(a>2, a, -1)
print(b)

In [ ]:
a = np.array([10,20,30,40,50,60,19,30,31,61])
#compute indices where the condition is true  . number has to divisible with 2
even  = np.argwhere(a%2==0).flatten()
print(even)
#you want to see the values
a_even = a[even]
print(a_even)

**07-01-25**

In [ ]:
"""Revision
1. Numpy array differences
2. why numpy arrays are faster
3. DOT product with 1d array and 2d array
4. how to explore an arrays?
     a.np.shape
     b.np.ndim
     c.np.size
     d.np.dtypes
     c.np.itemsize
5.Boolean indexing, broadcasting, transpose,dia,np.linalg.det(), np.linalg.inv()
     """

**Reshaping of an array**

In [1]:
import numpy as np

In [ ]:
#create an arrray of range of 1 to 7
a=np.arange(1,7)
print(a)

[1 2 3 4 5 6]


In [ ]:
#reshapethe above array in to 2 rowa and 3 columns?
b=a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


**New Axis**

In [ ]:
#new axis:-used to create new axis in the data
print(a.shape)
d=a[np.newaxis,:]
print(d)

(6,)
[[1 2 3 4 5 6]]


In [ ]:
d.shape

(1, 6)

In [ ]:
e=a[:,np.newaxis]
print(e)
e.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [ ]:
#why we are using np.newaxis?
#needed when the model requires the data to be shaped in a certain manner
#Note:- Transpose can be applicable for 2d_array

**Concatenation**

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.array([[9,10],[11,12]])
#combine or concatenate the above 2 arrays in 1d_array
c=np.concatenate((a,b,c),axis=None)
print(c)
"""Note:- 1.When axis=None it returns 1d array
          2.When axis=0 it adds second array values in to rows wise
          3.When axis=1 it adds the second array values in to columns side by side"""

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.array([[9,10],[11,12]])
#combine or concatenate the above 2 arrays in 1d_array
c=np.concatenate((a,b,c),axis=0)
print(c)
print(c[2,:])
print(c[:,1])


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[5 6]
[ 2  4  6  8 10 12]


**Hstack**

In [ ]:
#Hstack:- stack array in sequence horizontally
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
#c=np.concatenate((a,b),axis=none)
c=np.hstack((a,b))
print(c)
c.shape

[1 2 3 4 5 6 7 8]


(8,)

**Vstack:-** add the sequence of tack arrays vertically

In [ ]:
d=np.vstack((a,b))
d

In [ ]:
d=np.concatenate((a,b),axis=0)
d

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
d=np.hstack((a,b))
d


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#copying

In [ ]:
a=np.array([1,2,3])
b=a
b[0]=32
print(a)

[32  2  3]


In [ ]:
a=np.array([1,2,3])
b=a.copy()
b[0]=6
print(a)
#By usingcopy() if you make any change to new array the old array does not change

[1 2 3]


**Data types**

In [ ]:
#How can you find data types inthe array?
a=np.array([12,3])
a.dtype

In [ ]:
#store the above array in 32 bits
#how can you find data types in the array?
a=np.array([1,2,3],dtype=np.int32)
a.dtype

dtype('int32')

In [ ]:
#convert the data into float
a=np.array([1,2,3],dtype=np.float32)
a.dtype
a

array([1., 2., 3.], dtype=float32)

#Generating of arrays

In [ ]:
#generate an array of zeros which is having 2rows and 3 cols?
a=np.zeros((2,3))
print(a)

In [ ]:
#generate an array of ones which is having 2 rows amd 3 col
b=np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#generating an array of an specific number with specific rows and columns
c=np.full((3,3),5)
c

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
#generate an indentity matrix
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [ ]:
#generate an array of numbers up to 10
e = np.arange(1,11)
print(e)

In [ ]:
#linspace:- splits the data in to equal parts
h = np.linspace(0,10,5)
#np.lionspace(start,end,split_count)
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**08-01-2025**

In [ ]:
import numpy as np

In [ ]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None, like=None)
#N---> rows
#M --> Count of columns
#K --> index from where the '1' can be set in column index
#print a matrix with 3*5 idetntity matrix
b = np.eye(5,M=5,k=0)
print(b)

In [ ]:
#argwhere, argmin,argmax--> returns the indexes

#Random Numbers

In [ ]:
#Generate a random numbers uniformly distributed from 0 to 1?
a = np.random.random((3,2))
print(a)

In [ ]:
#Generate an array which is normally distributed?
#Normal distribution means---> mean, median,mode is same, variance is 1
b = np.random.randn(3,2)
print(b)

In [ ]:
print(np.mean(b))
print(np.var(b))
print(np.std(b))

In [3]:
#generate random.randn numbers upto 1000 samples  find the mean,varience and std
c = np.random.randn(1000)
print(c.mean(),c.var(),c.std())

-0.02112858888575277 0.9375729843467842 0.968283524772979


In [ ]:
#generate an random intgers from 10 to 20 in the size of 4*4
#random.randint(low, high=None, size=None, dtype=int)
d = np.random.randint(10, size = (4,4))
print(d)

In [ ]:
d = np.random.randint(10,20,size=(4,4))
print(d)

In [ ]:
#generate a number up to 6 and divide in to size of 10
e = np.random.choice(7,size=10)
print(e)

In [ ]:
l = np.random.choice([1,2,3,4],size = 10)
print(l)

### **solving linear equations**

In [ ]:
#2x1 + 3y1 = 0
#6x + 12y  = 5
a = np.array([[2,3],[6,12]])
b = np.array([0,5])
#  ax = B <==>  x = a**-1 b
x = np.linalg.inv(a).dot(b)
print(x)

**09-01-2025**

Overall revision

In [ ]:
#what is a numpy?
#How do you create a 1d array?
import numpy as np
arr = np.array([1,2,3,4])
print(arr.ndim)

In [ ]:
#what is difference between a list and Numpy array?
#arrays we cannot add extram items to exisiting array
#where as in list we can add new items to exiting list
#array's are having fixed memory
#arrays are homogenous and list is heterogenous

In [ ]:
#How do you check the shape and size of an numpy array?
""" np.size
    np.shape"""

In [ ]:
#How do you reshape an array?
a = np.array([1,2,3,4,5,6])
#change the above array in to 3 rows and 2 columns
b = a.reshape(3,2)
print(b)

In [ ]:
#How do you create an array of all zeros and all ones?
a = np.zeros((3,2))
print(a)
b = np.ones((4,4))
print(b)

In [ ]:
#what is broad casting in Numpy?
#it allows the arthematic operation between arrays of different sizes
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([2])
print(a*b)   # try -->   +,-,%,**

In [ ]:
#how can find the mean,median, std?
a = np.array([[1,2,3,4],[5,6,7,8]])
print(np.mean(a))

b = np.array([1,2,3,4,5,6,7,9])
print(np.median(b))

print('std for array a:',np.std(a))
print('std for array b:',np.std(b))

In [ ]:
#how can we utilize Numpy to quickly query our numerical data and perform actions based on boolean statement?
a = np.array([20,30,16,17,18,22,23,24,25,32])
#from the above array check the age group people who is having >= 18 print 'true' else 'flase'
b = np.where(a>=18, 'True','False')
print(b)

In [ ]:
#How can you compute the rolling statistics  using Numpy,  such as rolling mean?
from numpy.lib.stride_tricks import sliding_window_view
x = np.arange(6)
# print(x)
v = sliding_window_view(x,3)
print(v)

In [ ]:
#generate a random number which is uniformaly distributed --> 0 to 1
a = np.random.random((3,2))
#b = np.random.uniform((3,2))
a

In [ ]:
b = np.random.randn(3,2)
b

In [ ]:
c = np.random.choice([1,2,3,4],size =10)
print(c)

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a)
#access the '8'
print(a[1,2])
print(a[0,:])   #print the entire values of 1st column

In [ ]:
#what is a dot product?
#dimesions must be same and it equal of number of elements
a = np.array([[1,2,3,4],[1,2,3,4]])
b = np.array([[6,7,8,9],[9,7,6,5]])
c = b.T
d = np.dot(a,c)
print(d)

In [ ]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
d = a @ b
print(d)